[phases.build]
# Customize the PHP configuration
cmds = ['...',
    "echo \"<<<<<<<<<<<<< CHANGING THE PHP INI >>>>>>>>>>>>>>\"" ,
    "PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}') && echo -e '\\nupload_max_filesize = 50M\\npost_max_size = 50M\\nmemory_limit = 256M\\nmax_execution_time = 300' >> $PHP_INI_PATH",
]
